B
smorlos/swedishdem pull request #3
Opened 2018-01-31 23:11 UTC by smorlos

Wyrzuciłem połowe pliku html z projektu swedishdem, bo wyglądało to okropnie, mam nadzieję, że teraz jest trochę lepiej. 

Nadal zmagam się z pozycjonowaniem elementów(co widać w komentarzach w pliku styli).

Cały czas do przodu, chociaż dziś był krok w tył:)

2018-02-03 10:47 UTC, piotrkorlaga requested changes
Ogólnie jeszcze:
* PR powinieneś robić zawsze odbijaąc nowy branch od mastera, a nie jeden po drugim.
* nazwy branchy są nie do przyjęcia - nie możesz robić takiego chaosu, że nazywasz branch jedna literą
* Potrzebujemy Plan featuer'ów, które robisz w swoim projekcie i każdy feature to nowy branch i nowy PR. Proponuje konwencje nazwy brancha na: feature/[NR_ISSUE_Z_GH]-nazwa-odzielona-myślinikami

2018-02-03 10:47 UTC, piotrkorlaga commented on desktop.ini
> +[ViewState]
Ten plik jest niepotrzebny. Powinien trafić do gitignore.
👍 podoba mi się, że powstał plik baza.docx, ale porpobuje, żeby te zadania, które tam są napisane jeszcze trochę rozwinąć i przenieść do Github Issues

2018-02-03 10:47 UTC, piotrkorlaga commented on index.html
> +
niepotrzebne nowe linie

2018-02-03 10:47 UTC, piotrkorlaga commented on index.html
> +
niepotrzebne nowe linie

2018-02-03 10:47 UTC, piotrkorlaga commented on index.html
> +			<li class="main_menu_option">Option1</li>
👍 fajnie, że stosujesz klasy CSS. To dużo lepsza praktyka niż inlinowanie styli

2018-02-03 10:47 UTC, piotrkorlaga commented on index.html
> +		<article class="demo">
źle sformatowane - brak wciecia i ciągle powtarzają niepotrzben nowe linie

2018-02-03 10:47 UTC, piotrkorlaga commented on index.html
> +			<div><img  src="exemplarydemot.jpg" alt="przykladowy"></div>
- tag img jest niezamkniety. 
- obrazki powinny być przeniesione do wspólnego katalogu img
- nazwy plików jpg niech mówią jaka jest różnica zamiast różnić się tylko cyfrą 2 na końcu

2018-02-03 10:47 UTC, piotrkorlaga commented on index.html
> +			<div class="article_button">	Good</div> 	<!-- ocena na plus -->
jeżeli to jest button to powinien być użyty tag <button> a nie <div>

2018-02-03 10:47 UTC, piotrkorlaga commented on index.html
> +			<div class="article_button">	Bad</div> 	<!-- ocena na minus-->
niepotrzebne spacje miedzy tagiem a napisem Bad

2018-02-03 10:47 UTC, piotrkorlaga commented on index.html
> +			<div style="clear:both;"></div>
nie używajmy tagu style. Wszystkie style powinny być w pliku CSS

2018-02-03 10:47 UTC, piotrkorlaga commented on index.html
> +			<div class="article_button">	Share on fb</div>	<!--link do share na fb-->
zwyczajowo przyjeta konwencja w nazwach klas CSS to snake case czyli powinno być: article-button

2018-02-03 10:47 UTC, piotrkorlaga commented on style.css
> +#menu{
nie dodawaj martwego kodu, czyli takiego kodu, który nic nie robi. Puste selektory są zbędne

2018-02-03 10:47 UTC, piotrkorlaga commented on style.css
> +
usunąć te nowe linie na końcu pliku. Dbaj bardziej o estetykę kodu - proszę

2018-02-03 10:47 UTC, piotrkorlaga commented on style.css
> +	/*
nic commitujemy zakomentowanego kodu

2018-02-03 10:47 UTC, piotrkorlaga commented on w3schools/index.html
> +<meta http-equiv="refresh" content="30"> <!-- służy do odświeżania strony o daną ilość sekund ~https://www.w3schools.com/html/html_head.asp*/-->
https://en.wikipedia.org/wiki/Meta_refresh
tl;dr Use of meta refresh is discouraged by the World Wide Web Consortium (W3C), since unexpected refresh can disorient users.

Nie używałbym tego :)

2018-02-03 10:47 UTC, piotrkorlaga commented on w3schools/style.css
> +{
powinno być body{

2018-02-03 10:47 UTC, piotrkorlaga commented on w3schools/style.css
> +	font-size:70px;
używaj jednostek względnych rem. Zamiast pixeli. I pocztaj o typografi: https://zellwk.com/blog/responsive-typography/

2018-02-03 10:47 UTC, piotrkorlaga commented on w3schools/style.css
> +#reszta{
taka nazwa jak "reszta" nic mi nie mówi i trzymajmy się nazwy klas po angielsku

2018-02-03 10:47 UTC, piotrkorlaga commented on w3schools/style.css
> +	height: 20px;
używaj em zamiast pixeli gdzie się da

2018-02-03 10:47 UTC, piotrkorlaga commented on w3schools/style.css
> +	border-color:white;
kolor możesz podać w linijce border

2018-02-03 10:47 UTC, piotrkorlaga commented on w3schools/style.css
> +	margin-top:-10px;
unikałbym marginów na minusie - jeżeli musisz ich użyć tzn ze masz coś źle ostylowane wcześniej

2018-02-03 16:21 UTC, smorlos commented on w3schools/style.css
> +	margin-top:-10px;
To akurat był taki "feature", znalazłem to tutaj https://www.youtube.com/watch?v=SctdZr6CobQ i chciałem spróbować

2018-02-03 16:24 UTC, smorlos commented on w3schools/style.css
> +	height: 20px;
Sir yes sir :+1:  Widziałem te oznaczenia "em", ale wydawało się to dosyć skomplikowane w tym kursie i chciałem obczaić to dokładnie po dotarciu do flexboxa, żeby całość była responsywna :) Na w3 jest to opisane bez obrazowych przykładów https://www.w3schools.com/css/css_font.asp

2018-02-03 16:24 UTC, smorlos commented on w3schools/style.css
> +	border-color:white;
Dzięki

2018-02-03 16:26 UTC, smorlos commented on w3schools/style.css
> +#reszta{
Nie wiem co mnie podkusiło :+1:

2018-02-03 17:12 UTC, smorlos commented on w3schools/style.css
> +	font-size:70px;
Ale czad, byłem pewien, że to się robi Javascriptem :D

2018-02-03 17:13 UTC, smorlos commented on w3schools/index.html
> +<meta http-equiv="refresh" content="30"> <!-- służy do odświeżania strony o daną ilość sekund ~https://www.w3schools.com/html/html_head.asp*/-->
To był taki bajer do nauczenia się, że coś takiego jest:-)

2018-02-03 17:13 UTC, smorlos commented on w3schools/style.css
> +{
:+1:

2018-02-03 17:13 UTC, smorlos commented on style.css
> +
O fragmentach z przerwami Ci dziś opowiem z czego wynikają:)

2018-02-03 17:13 UTC, smorlos commented on index.html
> +			<div class="article_button">	Share on fb</div>	<!--link do share na fb-->
Dzięki!

2018-02-03 17:15 UTC, smorlos commented on index.html
> +			<div class="article_button">	Good</div> 	<!-- ocena na plus -->
Wiem, planowałem zrobić oba, ale dopiero po ustawieniu elementów tak jak chciałem(a tego mi się nie udało zrobić :D )

2018-02-04 13:40 UTC, piotrkorlaga requested changes

2018-02-04 13:40 UTC, piotrkorlaga commented on index.html
> +				<div class="article_button">	Good</div> 	<!-- ocena na plus -->
umówiliśmy się, że trzymamy się konwencji snake-case w nazwach klass css. Czyli nie article_button tylko article-button itd.

2018-02-04 13:40 UTC, piotrkorlaga commented on .gitignore
> +deskop.ini
zamień na *.ini . Poza tym musisz najpierw usunąć ten plik i zacommitować jego usunięcie

2018-02-05 06:31 UTC, piotrkorlaga approved these changes

2018-02-05 06:31 UTC, merged